name: Publish

on:
  release:
    types: [published]

concurrency:
  group: publish-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
    uses: krudi/reusable-actions/.github/workflows/publish-vscode.yaml@main
    with:
      node_version_file: .nvmrc
      install_command: npm ci
      check_command: npm run lint:prettier
      package_command: npx @vscode/vsce package
      publish_command: npx @vscode/vsce publish -p "$VSCE_PAT"
      vsce_glob: "*.vsix"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
